config/routes.rb
Rails.application.routes.draw do
  
  resources :events do
    resources :bookings, only: [:create]
  end
  resources :venues
  devise_for :users

  get 'bookings/index'
  root 'welcomes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :venue
  belongs_to :user
  has_many :bookings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :venues, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :bookings, dependent: :destroy

  def first_name_from_email
    email.split("@").first.capitalize
  end

  def admin?
    admin
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    before_action :authenticate_user!

    def index
        @bookings = Booking.includes(:user).where(user: current_user).all
    end

    def create
        @event = Event.find(params[:event_id])

        @service = BookingService.new(@event, current_user)
        status,result = @service.call


        case status
        when :success
            @booking = result
            redirect_to event_path(@event), notice: "Event booked successfully!"
        when :error
            redirect_to event, alert: "Booking failed: #{result.to_s.humanize}"
        end
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    if current_user.admin? 
      @events = Event.all
    else
      @events = Event.includes(:user).where(user: current_user).all
    end
  end

  # GET /events/1 or /events/1.json
  def show
    
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    authorize @event

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :description, :start_time, :end_time, :venue_id, :user_id)
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_venue, only: %i[ show edit update destroy ]

  # GET /venues or /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1 or /venues/1.json
  def show

  end

  # GET /venues/new
  def new
    @venue = Venue.new
    authorize @venue
  end

  # GET /venues/1/edit
  def edit
    authorize @venue
  end

  # POST /venues or /venues.json
  def create
    @venue = current_user.venues.build(venue_params)
    authorize @venue

    respond_to do |format|
      if @venue.save
        format.html { redirect_to venue_url(@venue), notice: "Venue was successfully created." }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1 or /venues/1.json
  def update
    authorize @venue
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to venue_url(@venue), notice: "Venue was successfully updated." }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1 or /venues/1.json
  def destroy
    authorize @venue
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to venues_url, notice: "Venue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def venue_params
      params.require(:venue).permit(:name, :address, :capacity, :user_id)
    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/bookings/index.html.erb
<h1>Your Bookings </h1>

<table class="table">
    <thead>
        <tr>
            <th>No.</th>
            <th>Event</th>
            <th> Status</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <% @bookings.each_with_index do |booking,index|%>
            <td><%= index + 1%></td>
            <td><%= link_to booking.event.name, event_path(booking.event.id) %></td>
            <td><%= booking.status %></td>
            <% end %>
        </tr>
    </tbody>
</table>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
<% if event.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

    <ul>
        <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :event_name %>
</div>

<div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :event_description %>
</div>

<div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :event_start_time %>
</div>

<div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, id: :event_end_time %>
</div>

<div class="field">
    <%= form.label :venue_id %>
    <%= form.collection_select :venue_id, Venue.all, :id, :name, {prompt: "Select Venue"}, id: :event_venue_id %>
</div>

<div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :name, {prompt: "Select Client"}, id: :event_user_id %>
</div>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Start time</th>
            <th>End time</th>
            <th>Venue</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @events.each do |event| %>
        <tr>
            <td><%= event.name %></td>
            <td><%= event.start_time %></td>
            <td><%= event.end_time %></td>
            <td><%= event.venue.name %></td>
            <td><%= link_to 'Show', event %></td>
            <td><%= link_to 'Edit', edit_event_path(event) %></td>
            <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Name:</strong>
    <%= @event.name %>
</p>

<p>
    <strong>Description:</strong>
    <%= @event.description %>
</p>

<p>
    <strong>Start time:</strong>
    <%= @event.start_time %>
</p>

<p>
    <strong>End time:</strong>
    <%= @event.end_time %>
</p>

<p>
    <strong>Venue:</strong>
    <%= @event.venue.name %>
</p>

<p>
    <strong>User:</strong>
    <%= @event.user.name %>
</p>

<%= link_to 'Edit', edit_event_path(@event), class: "btn btn-warning" %> |
<%= link_to 'Back', events_path, class:"btn btn-secondary" %> |
<%= button_to "Book this Event", event_bookings_path(@event), method: :post, class: "btn btn-success" %>

app/views/layouts/_navigation.html.erb
<nav class="user-navigation">
    <% if user_signed_in? %>
    Welcome, <strong><%= current_user.first_name_from_email || current_user.email %></strong>! |
    <%= link_to 'Edit profile', edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %> |
    <%= link_to "Home", root_path %>
    <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>EventVenueManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render "layouts/navigation" %>
    <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
    </div>
</body>

</html>

app/views/venues/_form.html.erb
<%= form_with(model: venue, local: true) do |form| %>
<% if venue.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

    <ul>
        <% venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :venue_name %>
</div>

<div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :venue_address %>
</div>

<div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity, id: :venue_capacity %>
</div>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Venues</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Capacity</th>
            <th>User</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @venues.each do |venue| %>
        <tr>
            <td><%= venue.name %></td>
            <td><%= venue.address %></td>
            <td><%= venue.capacity %></td>
            <td><%= venue.user.first_name_from_email %></td>
            <td><%= link_to 'Show', venue %></td>
            <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
            <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path, class: "btn btn-success" %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @venue.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @venue.address %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @venue.capacity %>
</p>

<p>
  <strong>User:</strong>
  <%= @venue.user %>
</p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>

app/views/welcomes/index.html.erb
<h1>Welcomes To Event Manager Application</h1>

<% if user_signed_in? %>
<%if current_user.admin? %>
<%= link_to "Add Event", new_event_path, class: "btn btn-success" %> |
<%= link_to "View Your Events", events_path, class: "btn btn-warning" %> |
<%= link_to "View Your Bookings", bookings_index_path, class: "btn btn-danger"%>
<% else %>
<%= link_to "View Your Events", events_path, class: "btn btn-warning" %> |
<%= link_to "View Your Bookings", bookings_index_path, class: "btn btn-danger"%>
<% end %>
|
<%= link_to "Venues", venues_path, class: "btn btn-info"  %>
<% end %>